2018-01-09 20:09:15,898 ERROR: Exception on /reset_password_request [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/git_local/microblog/app/routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "/home/jb/git_local/microblog/app/email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/jb/git_local/microblog/app/models.py", line 71, in get_reset_password_token
    return jwt.encode(
NameError: name 'jwt' is not defined
2018-01-09 20:10:43,634 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:11:26,176 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:11:42,382 ERROR: Exception on /reset_password_request [POST] [in /home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jb/git_local/microblog/app/routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "/home/jb/git_local/microblog/app/email.py", line 27, in send_password_reset_email
    user=user, token=token))
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/jb/.virtualenvs/flask_mega_tutorial/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_pasword.html
2018-01-09 20:13:12,679 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:15:13,805 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:18:42,790 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:32:21,263 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:32:24,423 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:34:35,896 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:36:58,125 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
2018-01-09 20:39:22,548 INFO: Microblog startup [in /home/jb/git_local/microblog/app/__init__.py:45]
